
package com.mycompany.medconncet;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiago
 */
public class ConsultaFila extends javax.swing.JFrame {

    private static int currentIndex = 0;
    
    
    public ConsultaFila() {
        initComponents();
        
     
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botãoExcl2 = new Modelos.BotãoExcl();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        C3 = new javax.swing.JTextField();
        ProxA = new Modelos.Botão();
        botão2 = new Modelos.Botão();
        Del = new Modelos.Botão();
        Volta4 = new javax.swing.JButton();
        botão1 = new Modelos.Botão();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1346, 862));
        getContentPane().setLayout(null);

        E1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        E1.setText("    P1645");
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        getContentPane().add(E1);
        E1.setBounds(190, 290, 333, 120);

        E2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        E2.setText("    C7812");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        getContentPane().add(E2);
        E2.setBounds(190, 430, 333, 120);

        E3.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        E3.setText("    R5482");
        getContentPane().add(E3);
        E3.setBounds(190, 570, 333, 120);

        C2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        C2.setText("    C1546");
        C2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                C2ComponentRemoved(evt);
            }
        });
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        getContentPane().add(C2);
        C2.setBounds(840, 430, 333, 120);

        C1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        C1.setText("    P1547");
        getContentPane().add(C1);
        C1.setBounds(840, 290, 333, 120);

        C3.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        C3.setText("    R2543");
        getContentPane().add(C3);
        C3.setBounds(840, 570, 333, 120);

        ProxA.setBackground(new java.awt.Color(19, 107, 105));
        ProxA.setBorder(null);
        ProxA.setForeground(new java.awt.Color(255, 255, 255));
        ProxA.setText("Próximo Atendimento");
        ProxA.setBorderColor(new java.awt.Color(19, 107, 105));
        ProxA.setColor(new java.awt.Color(19, 107, 105));
        ProxA.setColorClick(new java.awt.Color(19, 107, 105));
        ProxA.setColorOver(new java.awt.Color(19, 107, 105));
        ProxA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ProxA.setRadius(65);
        ProxA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProxAActionPerformed(evt);
            }
        });
        getContentPane().add(ProxA);
        ProxA.setBounds(60, 730, 273, 71);

        botão2.setBackground(new java.awt.Color(19, 107, 105));
        botão2.setBorder(null);
        botão2.setForeground(new java.awt.Color(255, 255, 255));
        botão2.setText("Próximo Resultado");
        botão2.setBorderColor(new java.awt.Color(19, 107, 105));
        botão2.setColor(new java.awt.Color(19, 107, 105));
        botão2.setColorClick(new java.awt.Color(19, 107, 105));
        botão2.setColorOver(new java.awt.Color(19, 107, 105));
        botão2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botão2.setRadius(65);
        botão2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2ActionPerformed(evt);
            }
        });
        getContentPane().add(botão2);
        botão2.setBounds(620, 730, 273, 71);

        Del.setBackground(new java.awt.Color(19, 107, 105));
        Del.setBorder(null);
        Del.setForeground(new java.awt.Color(255, 255, 255));
        Del.setText("Limpar Fila");
        Del.setBorderColor(new java.awt.Color(19, 107, 105));
        Del.setColor(new java.awt.Color(19, 107, 105));
        Del.setColorClick(new java.awt.Color(19, 107, 105));
        Del.setColorOver(new java.awt.Color(19, 107, 105));
        Del.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Del.setRadius(65);
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });
        getContentPane().add(Del);
        Del.setBounds(1020, 730, 273, 71);

        Volta4.setForeground(new java.awt.Color(255, 255, 255));
        Volta4.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\de-volta.png")); // NOI18N
        Volta4.setBorder(null);
        Volta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volta4ActionPerformed(evt);
            }
        });
        getContentPane().add(Volta4);
        Volta4.setBounds(100, 130, 90, 60);

        botão1.setBackground(new java.awt.Color(19, 107, 105));
        botão1.setForeground(new java.awt.Color(255, 255, 255));
        botão1.setText("Próxima Consulta");
        botão1.setBorderColor(new java.awt.Color(19, 107, 105));
        botão1.setColor(new java.awt.Color(19, 107, 105));
        botão1.setColorClick(new java.awt.Color(19, 107, 105));
        botão1.setColorOver(new java.awt.Color(19, 107, 105));
        botão1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botão1.setRadius(65);
        botão1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão1ActionPerformed(evt);
            }
        });
        getContentPane().add(botão1);
        botão1.setBounds(340, 730, 273, 71);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\Fila.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
  
           }//GEN-LAST:event_C2ActionPerformed
 
    private void C2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_C2ComponentRemoved
        
    }//GEN-LAST:event_C2ComponentRemoved

    private void ProxAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProxAActionPerformed
             
        
        
                String textoCampo1 = E1.getText();
                C1.setText(textoCampo1);
                E1.setText("");
             
    }//GEN-LAST:event_ProxAActionPerformed

    private void botão2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2ActionPerformed
                String textoCampo3 = E3.getText();
                C3.setText(textoCampo3);
                E3.setText("");      
    }//GEN-LAST:event_botão2ActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
      C2.setText("");
      C1.setText("");
      C3.setText("");
    }//GEN-LAST:event_DelActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
      
    }//GEN-LAST:event_E1ActionPerformed

    private void Volta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volta4ActionPerformed
       Menu mn  = new Menu();
       mn.setVisible(true);
       dispose();
    }//GEN-LAST:event_Volta4ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E2ActionPerformed

    private void botão1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão1ActionPerformed
                String textoCampo3 = E2.getText();
                C2.setText(textoCampo3);
                E2.setText("");      
    }//GEN-LAST:event_botão1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaFila().setVisible(true);
            }
        });
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C1;
    public javax.swing.JTextField C2;
    private javax.swing.JTextField C3;
    private Modelos.Botão Del;
    public javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private Modelos.Botão ProxA;
    private javax.swing.JButton Volta4;
    private Modelos.Botão botão1;
    private Modelos.Botão botão2;
    private Modelos.BotãoExcl botãoExcl2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
