/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medconncet;


import static com.mycompany.medconncet.Senha3.gerarSenha3;


/**
 *
 * @author tiago
 */
public class SenhaPref extends javax.swing.JFrame {

    /**
     * Creates new form SenhaPref
     */
    public SenhaPref() {
        initComponents();
          Volta5.setBackground(new java.awt.Color(0,0,0,1));
          Senha.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new Modelos.TextField();
        gerarSenha2 = new Modelos.Botão();
        Senha = new javax.swing.JTextField();
        Volta5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 890));
        getContentPane().setLayout(null);

        textField1.setBorder(null);
        textField1.setLineColor(new java.awt.Color(255, 255, 255));
        textField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1);
        textField1.setBounds(90, 370, 814, 65);

        gerarSenha2.setBorder(null);
        gerarSenha2.setForeground(new java.awt.Color(255, 255, 255));
        gerarSenha2.setText("Confirmar");
        gerarSenha2.setBorderColor(new java.awt.Color(19, 107, 105));
        gerarSenha2.setColor(new java.awt.Color(19, 107, 105));
        gerarSenha2.setColorClick(new java.awt.Color(19, 107, 105));
        gerarSenha2.setColorOver(new java.awt.Color(19, 107, 105));
        gerarSenha2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gerarSenha2.setRadius(65);
        gerarSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarSenha2ActionPerformed(evt);
            }
        });
        getContentPane().add(gerarSenha2);
        gerarSenha2.setBounds(940, 370, 244, 65);

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Senha);
        Senha.setBounds(460, 520, 333, 120);

        Volta5.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\de-volta.png")); // NOI18N
        Volta5.setBorder(null);
        Volta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volta5ActionPerformed(evt);
            }
        });
        getContentPane().add(Volta5);
        Volta5.setBounds(70, 110, 70, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\AtendimentoPref.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void gerarSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarSenha2ActionPerformed
            ConsultaFila cf = new ConsultaFila();
            cf.E1.setText(Senha.getText());
            cf.setVisible(true);
            dispose();
            
        String gerarSenha3 = gerarSenha3 (4); 
         Senha.setText(gerarSenha3); 
    }//GEN-LAST:event_gerarSenha2ActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void Volta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volta5ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_Volta5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenhaPref.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenhaPref.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenhaPref.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenhaPref.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SenhaPref().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Senha;
    private javax.swing.JButton Volta5;
    private Modelos.Botão gerarSenha2;
    private javax.swing.JLabel jLabel1;
    private Modelos.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
