/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medconncet;


import static com.mycompany.medconncet.Senha4.gerarSenha4;


/**
 *
 * @author tiago
 */
public class SenhaExam extends javax.swing.JFrame {

    /**
     * Creates new form SenhaExam
     */
    public SenhaExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new Modelos.TextField();
        gerarSenha3 = new Modelos.Botão();
        Senha3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textField1.setLineColor(new java.awt.Color(255, 255, 255));
        textField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField1);
        textField1.setBounds(90, 370, 814, 65);

        gerarSenha3.setBorder(null);
        gerarSenha3.setForeground(new java.awt.Color(255, 255, 255));
        gerarSenha3.setText("Confirmar");
        gerarSenha3.setBorderColor(new java.awt.Color(19, 107, 105));
        gerarSenha3.setColor(new java.awt.Color(19, 107, 105));
        gerarSenha3.setColorClick(new java.awt.Color(19, 107, 105));
        gerarSenha3.setColorOver(new java.awt.Color(19, 107, 105));
        gerarSenha3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gerarSenha3.setRadius(65);
        gerarSenha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarSenha3ActionPerformed(evt);
            }
        });
        getContentPane().add(gerarSenha3);
        gerarSenha3.setBounds(960, 370, 244, 65);

        Senha3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(Senha3);
        Senha3.setBounds(480, 540, 333, 120);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\de-volta.png")); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 100, 80, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\ResultadoExa.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1348, 870);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerarSenha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarSenha3ActionPerformed
               
        
        
       String gerarSenha4 = gerarSenha4(5); 
       Senha3.setText(gerarSenha4);   
    }//GEN-LAST:event_gerarSenha3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenhaExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenhaExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenhaExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenhaExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SenhaExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Senha3;
    private Modelos.Botão gerarSenha3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private Modelos.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
