/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medconncet;


import static com.mycompany.medconncet.Senha2.gerarSenha2;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author tiago
 */
public class Senha extends javax.swing.JFrame {

    /**
     * Creates new form Tela5
     */
    public Senha() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaTx = new Modelos.TextField();
        BotãoVolta4 = new javax.swing.JButton();
        gerarSenha = new Modelos.Botão();
        Senha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1346, 862));
        getContentPane().setLayout(null);

        CaixaTx.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CaixaTx.setLineColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(CaixaTx);
        CaixaTx.setBounds(120, 380, 814, 65);

        BotãoVolta4.setForeground(new java.awt.Color(255, 255, 255));
        BotãoVolta4.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\de-volta.png")); // NOI18N
        BotãoVolta4.setText("jButton1");
        BotãoVolta4.setBorder(null);
        BotãoVolta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVolta4ActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVolta4);
        BotãoVolta4.setBounds(110, 110, 90, 60);

        gerarSenha.setBackground(new java.awt.Color(19, 107, 105));
        gerarSenha.setForeground(new java.awt.Color(255, 255, 255));
        gerarSenha.setText("Confirmar");
        gerarSenha.setBorderColor(new java.awt.Color(19, 107, 105));
        gerarSenha.setColor(new java.awt.Color(19, 107, 105));
        gerarSenha.setColorClick(new java.awt.Color(19, 107, 105));
        gerarSenha.setColorOver(new java.awt.Color(19, 107, 105));
        gerarSenha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gerarSenha.setRadius(65);
        gerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(gerarSenha);
        gerarSenha.setBounds(980, 380, 244, 65);

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        Senha.setBorder(null);
        Senha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(Senha);
        Senha.setBounds(500, 530, 333, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Faculdade2\\MedConncet\\src\\main\\java\\Imagens\\Senha2.PNG")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotãoVolta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVolta4ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotãoVolta4ActionPerformed

    private void gerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarSenhaActionPerformed
       String gerarSenha2 = gerarSenha2 (4); 
       Senha.setText(gerarSenha2);        
    }//GEN-LAST:event_gerarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoVolta4;
    private Modelos.TextField CaixaTx;
    private javax.swing.JTextField Senha;
    private Modelos.Botão gerarSenha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
