/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medconncet;

/**
 *
 * @author tiago
 */
public class Tela3 extends javax.swing.JFrame {

    /**
     * Creates new form Tela3
     */
    public Tela3() {
        initComponents();
        Volta2.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volta2 = new javax.swing.JButton();
        botão1 = new Modelos.Botão();
        jPanel1 = new javax.swing.JPanel();
        A = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        B = new javax.swing.JButton();
        S = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        M = new javax.swing.JButton();
        Espaço = new javax.swing.JButton();
        cps = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        BackSpace = new javax.swing.JToggleButton();
        CaixaTx = new Modelos.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        Volta2.setIcon(new javax.swing.ImageIcon("F:\\Faculdade\\A3-4 semestre\\de-volta.png")); // NOI18N
        Volta2.setBorder(null);
        Volta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volta2ActionPerformed(evt);
            }
        });
        getContentPane().add(Volta2);
        Volta2.setBounds(80, 100, 64, 60);

        botão1.setBorder(null);
        botão1.setForeground(new java.awt.Color(255, 255, 255));
        botão1.setText("Confirmar");
        botão1.setBorderColor(new java.awt.Color(19, 107, 105));
        botão1.setColor(new java.awt.Color(19, 107, 105));
        botão1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botão1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão1ActionPerformed(evt);
            }
        });
        getContentPane().add(botão1);
        botão1.setBounds(980, 370, 244, 65);

        jPanel1.setLayout(null);

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        jPanel1.add(A);
        A.setBounds(30, 60, 60, 23);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        jPanel1.add(C);
        C.setBounds(30, 170, 60, 23);

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel1.add(D);
        D.setBounds(130, 60, 60, 23);

        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        jPanel1.add(E);
        E.setBounds(130, 110, 60, 23);

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        jPanel1.add(F);
        F.setBounds(130, 170, 60, 23);

        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        jPanel1.add(G);
        G.setBounds(230, 60, 60, 23);

        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        jPanel1.add(H);
        H.setBounds(230, 110, 60, 23);

        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        jPanel1.add(K);
        K.setBounds(330, 110, 60, 23);

        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel1.add(L);
        L.setBounds(330, 170, 60, 23);

        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        jPanel1.add(N);
        N.setBounds(440, 110, 60, 23);

        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        jPanel1.add(O);
        O.setBounds(440, 170, 60, 23);

        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel1.add(P);
        P.setBounds(530, 60, 60, 23);

        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        jPanel1.add(Q);
        Q.setBounds(530, 110, 60, 23);

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        jPanel1.add(R);
        R.setBounds(530, 170, 60, 23);

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel1.add(B);
        B.setBounds(30, 110, 60, 23);

        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        jPanel1.add(S);
        S.setBounds(630, 60, 60, 23);

        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        jPanel1.add(I);
        I.setBounds(230, 170, 60, 23);

        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        jPanel1.add(J);
        J.setBounds(330, 60, 60, 23);

        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        jPanel1.add(M);
        M.setBounds(440, 60, 60, 23);

        Espaço.setText("Espaço");
        jPanel1.add(Espaço);
        Espaço.setBounds(235, 260, 640, 23);

        cps.setText("CapsLock");
        cps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpsActionPerformed(evt);
            }
        });
        jPanel1.add(cps);
        cps.setBounds(930, 110, 110, 23);

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        jPanel1.add(T);
        T.setBounds(630, 110, 60, 23);

        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        jPanel1.add(U);
        U.setBounds(630, 170, 60, 23);

        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        jPanel1.add(V);
        V.setBounds(730, 60, 60, 23);

        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        jPanel1.add(W);
        W.setBounds(730, 110, 60, 23);

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        jPanel1.add(X);
        X.setBounds(730, 170, 60, 23);

        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        jPanel1.add(Y);
        Y.setBounds(830, 60, 60, 23);

        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        jPanel1.add(Z);
        Z.setBounds(830, 110, 60, 23);

        BackSpace.setText("Backspace");
        BackSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackSpaceMouseClicked(evt);
            }
        });
        BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSpaceActionPerformed(evt);
            }
        });
        jPanel1.add(BackSpace);
        BackSpace.setBounds(930, 60, 111, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 480, 1230, 300);

        CaixaTx.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CaixaTx.setLineColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(CaixaTx);
        CaixaTx.setBounds(100, 370, 814, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Faculdade\\A3-4 semestre\\AtendimentoPref.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1340, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volta2ActionPerformed
        Tela1 mn = new Tela1();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_Volta2ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        CaixaTx.setText(CaixaTx.getText()+A.getText());
    }//GEN-LAST:event_AActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        CaixaTx.setText(CaixaTx.getText()+C.getText());
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        CaixaTx.setText(CaixaTx.getText()+D.getText());
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        CaixaTx.setText(CaixaTx.getText()+E.getText());
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        CaixaTx.setText(CaixaTx.getText()+F.getText());
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        CaixaTx.setText(CaixaTx.getText()+G.getText());
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        CaixaTx.setText(CaixaTx.getText()+H.getText());
    }//GEN-LAST:event_HActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        CaixaTx.setText(CaixaTx.getText()+K.getText());
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        CaixaTx.setText(CaixaTx.getText()+L.getText());
    }//GEN-LAST:event_LActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        CaixaTx.setText(CaixaTx.getText()+N.getText());
    }//GEN-LAST:event_NActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        CaixaTx.setText(CaixaTx.getText()+O.getText());
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        CaixaTx.setText(CaixaTx.getText()+P.getText());
    }//GEN-LAST:event_PActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        CaixaTx.setText(CaixaTx.getText()+Q.getText());
    }//GEN-LAST:event_QActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        CaixaTx.setText(CaixaTx.getText()+R.getText());
    }//GEN-LAST:event_RActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        CaixaTx.setText(CaixaTx.getText()+B.getText());
    }//GEN-LAST:event_BActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        CaixaTx.setText(CaixaTx.getText()+S.getText());
    }//GEN-LAST:event_SActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        CaixaTx.setText(CaixaTx.getText()+I.getText());
    }//GEN-LAST:event_IActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        CaixaTx.setText(CaixaTx.getText()+J.getText());
    }//GEN-LAST:event_JActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        CaixaTx.setText(CaixaTx.getText()+M.getText());
    }//GEN-LAST:event_MActionPerformed

    private void cpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpsActionPerformed

    }//GEN-LAST:event_cpsActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        CaixaTx.setText(CaixaTx.getText()+T.getText());
    }//GEN-LAST:event_TActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        CaixaTx.setText(CaixaTx.getText()+U.getText());
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        CaixaTx.setText(CaixaTx.getText()+V.getText());
    }//GEN-LAST:event_VActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        CaixaTx.setText(CaixaTx.getText()+W.getText());
    }//GEN-LAST:event_WActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        CaixaTx.setText(CaixaTx.getText()+X.getText());
    }//GEN-LAST:event_XActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        CaixaTx.setText(CaixaTx.getText()+Y.getText());
    }//GEN-LAST:event_YActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        CaixaTx.setText(CaixaTx.getText()+Z.getText());
    }//GEN-LAST:event_ZActionPerformed

    private void BackSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackSpaceMouseClicked
        if (evt.getClickCount() == 2){

        }
        if (evt.getClickCount() == 1) {

        }
    }//GEN-LAST:event_BackSpaceMouseClicked

    private void BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackSpaceActionPerformed
        String bt;
        if(CaixaTx.getText().length()>0){
        }

        StringBuilder st = new StringBuilder(CaixaTx.getText());
        st.deleteCharAt(CaixaTx.getText().length()-1);
        bt = st.toString();
        CaixaTx.setText(bt);

    }//GEN-LAST:event_BackSpaceActionPerformed

    private void botão1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão1ActionPerformed
        Tela5 snh = new Tela5();
        snh.setVisible(true);
        dispose();
    }//GEN-LAST:event_botão1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JToggleButton BackSpace;
    private javax.swing.JButton C;
    private Modelos.TextField CaixaTx;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton Espaço;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton Volta2;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private Modelos.Botão botão1;
    private javax.swing.JButton cps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
